### PR TITLE
add bubble sort in javascript

### PR DESCRIPTION
**Pull request by MaxR522**

### CODE REVIEW

**Review by yehezkielermanto — CHANGES_REQUESTED** [review]
Hello, how can I run this file? kindly make the code in a single file, so you cannot export the function.

**Comment by MaxR522** [comment]
> Hello, how can I run this file? kindly make the code in a single file, so you cannot export the function.

Ok ! I will fix that

**Comment by MaxR522** [comment]
It is fixed by this commit [76d2c64](https://github.com/NoraNekoIT/algorithm-in-all-languages/pull/10/commits/76d2c643de662f7aa3a278e4c7891822331b1bd9)

**Comment by yehezkielermanto** [comment]
ok thank you...

**Pull request merged**
