### PR TITLE
created solution of merge-two-sorted-lists.cpp

### PR DESCRIPTION
**Pull request by RachitJain-Learner**

### CODE REVIEW

**Comment by RachitJain-Learner** [comment]
Hi buddy
please add label of Hacktoberfest as "hacktoberfest" instead of hactoberfest because hactoberfest spelling is wrong as k is missing

**Comment by NoraNekoIT** [comment]
> Hi buddy please add label of Hacktoberfest as "hacktoberfest" instead of "hactoberfest" because hactoberfest spelling is wrong as k is missing

Ok Sir thanks for comment

**Comment by RachitJain-Learner** [comment]
Please accept my pull request

**Review by NoraNekoIT — APPROVED** [review]
ok

**Pull request merged**
